spring:
  application.name: springPizza
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
imgur:
    clientId: 6a70b7b44ac815e

logging:
  level:
    root: info
  file:
    path: logs
    name: ${logging.file.path}/log-65.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"



